### ISSUE TITLE
Terraform shows an error if too many networks are supplied

### ISSUE THREAD

**Issue by snooops** [terraform-providers/terraform-provider-cloudstack#12]
### CloudStack Version
4.9.2.0-1.el7.centos
### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
- cloudstack_network

### Terraform Configuration Files
```hcl
resource "cloudstack_network" "Public" {
  name              = "Public"
  cidr              = "10.99.1.0/24"
  gateway           = "10.99.1.1"
  network_offering  = "Default VPC Network with LB"
  zone              = "${var.zone}"
  vpc_id            = "${cloudstack_vpc.myvpc.id}"
  project           = "${var.project}"
  acl_id            = "ebefcc96-75f5-11e7-adb3-e2bd27d4977e" # default static id of cloudstack
}

# repeat this part 10 times, change the cidr and name and stuff
resource "cloudstack_network" "network1" {
  name              = "network1"
  cidr              = "10.99.2.0/24"
  gateway           = "10.99.2.1"
  network_offering  = "${var.network_offering_internalwithrouter}"
  zone              = "${var.zone}"
  vpc_id            = "${cloudstack_vpc.myvpc.id}"
  project           = "${var.project}"
  acl_id            = "ebefcc96-75f5-11e7-adb3-e2bd27d4977e" # default static id of cloudstack
}
```

### Expected Behavior
terraform should not receive an error

### Actual Behavior
Terraforms returns some random network errors but at cloudstack all networks are valid and up and stable:

9 error(s) occurred:

* cloudstack_network.network5: 1 error(s) occurred:

* cloudstack_network.network5: Error creating network network5: invalid character '<' looking for beginning of value
* cloudstack_network.network3: 1 error(s) occurred:

* cloudstack_network.network3: Error creating network network3: invalid character '<' looking for beginning of value

### Steps to Reproduce
1. use the code snippet provided above to fit your cloudstack environment
2. copy and paste network1 for example 10 times.
3. `terraform apply`
4. verify the networks with your cloudstack gui

**Comment by apparentlymart** [comment]
Hi @snooops! Sorry this is failing in a useless way.

Often errors of this type result when an API returns an error using a different serialization format than is expected for successful responses. In this case, it looks like the API returned either HTML or XML where JSON was expected.

Running terraform with the environment variable `TF_LOG=debug` will produce verbose logging that might include more verbose information about what was sent to and received from the remote API, that might help explain what's going on here. If you could run Terraform again with that variable set and share the result, I think that'd make debugging easier here.

If you're running this on a "real" config containing sensitive information, do feel free to redact or remove certain information from the log. The important thing is to be able to see any log messages coming from the cloudstack provider about the requests it is making.

**Comment by svanharmelen** [comment]
@snooops I'm guessing you hit a CloudStack bug here. All your networks are created in parallel, and CloudStack is ok with that, but the router VM isn't.

I'm on holiday so only have my phone with me and cannot lookup the details easily. But you can verify my assumption by adding an explicit `depends_on` between each network. So network10 depends on network9, network9 depends on network8 and so on.

If my assumption is correct, you will not receive any errors with this config tweak/hack...

**Comment by snooops** [comment]
Ok, i tried it with depends_on and have set TF_LOG=debug, here is the output after the last working network:

cloudstack_network.network5: Creation complete (ID: 44b68d33-0595-4366-82f4-43fd19008eea)
2017/08/11 22:44:27 [DEBUG] dag/walk: walking "cloudstack_network.network6"
2017/08/11 22:44:27 [DEBUG] vertex 'root.cloudstack_network.network6': walking
2017/08/11 22:44:27 [DEBUG] vertex 'root.cloudstack_network.network6': evaluating
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalReadDiff
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalIf
2017/08/11 22:44:27 [DEBUG] root: eval: terraform.EvalNoop
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalIf
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalInterpolate
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalReadState
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalValidateResource
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalDiff
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalReadDiff
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalCompareDiff
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalReadState
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalApplyPre
2017/08/11 22:44:27 [DEBUG] root: eval: *terraform.EvalApply
2017/08/11 22:44:27 [DEBUG] apply: cloudstack_network.network6: executing Apply
cloudstack_network.network6: Creating...
2017/08/11 22:44:27 [DEBUG] plugin: terraform-provider-cloudstack_v0.1.1_x4: 2017/08/11 22:44:27 [DEBUG] No meta timeoutkey found in Apply()
  acl_id:           "" => "ebefcc96-75f5-11e7-adb3-e2bd27d4977e"
2017/08/11 22:44:27 [DEBUG] plugin: terraform-provider-cloudstack_v0.1.1_x4: 2017/08/11 22:44:27 [DEBUG] Retrieving ID of network_offering: VPC Default Network
  cidr:             "" => "10.230.6.0/24"
  display_text:     "" => "<computed>"
  endip:            "" => "<computed>"
  gateway:          "" => "10.230.6.1"
  name:             "" => "network6"
  network_domain:   "" => "<computed>"
  network_offering: "" => "VPC Default Network"
  project:          "" => "Meyer_TF"
  startip:          "" => "<computed>"
  tags.%:           "" => "<computed>"
  vpc_id:           "" => "85f00d12-bbe6-4127-9e9a-17c45b5b6201"
  zone:             "" => "Germany"
2017/08/11 22:44:27 [DEBUG] plugin: terraform-provider-cloudstack_v0.1.1_x4: 2017/08/11 22:44:27 [DEBUG] Retrieving ID of zone: Germany
2017/08/11 22:44:27 [DEBUG] plugin: terraform-provider-cloudstack_v0.1.1_x4: 2017/08/11 22:44:27 [DEBUG] Retrieving ID of project: Meyer_TF
2017/08/11 22:44:31 [DEBUG] dag/walk: vertex "root", waiting for: "provider.cloudstack (close)"
2017/08/11 22:44:31 [DEBUG] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "cloudstack_network.network6"
2017/08/11 22:44:31 [DEBUG] dag/walk: vertex "provider.cloudstack (close)", waiting for: "cloudstack_network.network6"
2017/08/11 22:44:33 [DEBUG] root: eval: *terraform.EvalWriteState
2017/08/11 22:44:33 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/08/11 22:44:33 [DEBUG] root: eval: *terraform.EvalIf
2017/08/11 22:44:33 [DEBUG] root: eval: *terraform.EvalWriteState
2017/08/11 22:44:33 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/08/11 22:44:33 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/08/11 22:44:33 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* cloudstack_network.network6: Error creating network network6: CloudStack API error 530 (CSExceptionErrorCode: 4250): Internal error executing command, please contact your system administrator
2017/08/11 22:44:33 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* cloudstack_network.network6: Error creating network network6: CloudStack API error 530 (CSExceptionErrorCode: 4250): Internal error executing command, please contact your system administrator
2017/08/11 22:44:33 [TRACE] [walkApply] Exiting eval tree: cloudstack_network.network6
2017/08/11 22:44:33 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/08/11 22:44:33 [DEBUG] dag/walk: upstream errored, not walking "provider.cloudstack (close)"
2017/08/11 22:44:33 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/08/11 22:44:33 [DEBUG] plugin: waiting for all plugin processes to complete...
Error applying plan:

1 error(s) occurred:

* cloudstack_network.network6: 1 error(s) occurred:

* cloudstack_network.network6: Error creating network network6: CloudStack API error 530 (CSExceptionErrorCode: 4250): Internal error executing command, please contact your system administrator

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by svanharmelen** [comment]
Hmm... OK, so it doesn't look like you are hitting the bug I was thinking about. But still you clearly receive a CloudStack error, so the root cause of this problem should be searched for in the CloudStack logs. That is the only place that will show the real problem/error.

Do you run CloudStack yourself, or do you use a hosted service? If you run CloudStack yourself you have all the logs available to find the root cause in there. If you use a hosted service I guess you would need to open a case with them to ask for more details.

As for the other error messages the received when running all the `createNetwork` calls in parallel, I still think this is (also) a CloudStack problem. My guess is that as soon as you get the first error (the one you see in your output above), the other calls are rejected or killed/errored in a non-normal way. Causing them to receive unexpected responses.

To double check you could run this again without the specific `depends_on`, but with `TF_LOG=TRACE` to see if it shows the other errors as well.

Either way, the real problem must be found/solved in CloudStack, that much is clear now.

**Comment by snooops** [comment]
Ok, i have found some Java exceptions at the management logs of cloudstack, i have reported them and will report the feedback if i get some ;)

**Comment by snooops** [comment]
Its hitting a limitation of the hypervisor. Im using XenServer which supports 7 NICs / VM (https://docs.citrix.com/content/dam/docs/en-us/xenserver/xenserver-7-0/downloads/xenserver-7-0-config-limits.pdf) . CloudStack dont handles the limitation correctly, thats the reason for this exception. There is already a ticket open: https://issues.apache.org/jira/browse/CLOUDSTACK-9999 

I guess you can close this one. Thanks for your help ;)

**Comment by svanharmelen** [comment]
Yes, this fits my expectations :wink: Thanks for the feedback!
