### ISSUE TITLE
Support source and destination CIDRs in cloudstack 4.10 egress firewall

### ISSUE THREAD

**Issue by brucegl** [terraform-providers/terraform-provider-cloudstack#20]
Hi there,

I couldn't see or work out if source and destination CIDRs are supported in cloudstack_egress_firewall. Not sure if cloudstack introduced a customer breaking change here in version 4.10. Thoughts and timescales would be very much appreciated.

Thanks

**Comment by brucegl** [comment]
Ah, I see I can just enter the source CIDR and omit the optional destination CIDR for now. My request is now more about support for cloudstack 4.10.

Thanks

**Comment by svanharmelen** [comment]
We just updated the provider (still needs be be released) to support CS 4.11.2.0, so that should fix this issue.
