### ISSUE TITLE
root_disk_size changed on cloud provider side isn't synced to state

### ISSUE THREAD

**Issue by saimonn** [terraform-providers/terraform-provider-cloudstack#27]
I updated my instance root disk size from 50 too 200GB on the cloud provider web interface (exoscale).
After running terraform plan, I expected the state to sync with the cloud provider API, but it still showed 50GB.

I fixed this with the workflow `terraform state pull | edit s/50/200/ | terraform state push`, but I think the provider cloud be fixed to handle that case.

**Comment by svanharmelen** [comment]
@saimonn a plan will not change/update your state file. In these cases a `terraform refresh` should do the trick... Could you try that one to confirm things work as expected?

**Comment by svanharmelen** [comment]
It does a dry-refresh, but this will not change/update your state file. It will only use the refreshed state in memory.

Fixed the problem in PR #28

**Comment by saimonn** [comment]
Thank for your quick PR !
