### ISSUE TITLE
Unable to create firewall rule for the IP address ID=## as IP is not associated with any network and no networkId is passed in

### ISSUE THREAD

**Issue by icornett** [terraform-providers/terraform-provider-cloudstack#30]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.11.3
+ provider.cloudstack v0.1.4

### Affected Resource(s)
Please list the resources as a list, for example:

- cloudstack_firewall

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# Full config at: https://gist.github.com/icornett/4bb51d43bf49891357f58cc39d09b618

resource "cloudstack_ipaddress" "k8s-ip" {
   network_id = "${cloudstack_network.k8s.id}"
   vpc_id     = "562142c9-5f70-4fd5-a4e1-eb73245011ac"
   is_portable   = false
}

resource "cloudstack_firewall" "k8s-firewall" {
   ip_address_id = "${cloudstack_ipaddress.k8s-ip.id}"
   managed       = true

   rule {
       cidr_list = ["0.0.0.0/0"]
       protocol  = "tcp"
       ports     = ["22", "2200-2202"]
   }
}

```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

https://gist.github.com/icornett/4bb51d43bf49891357f58cc39d09b618

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

Cloudstack Firewall should have built with passed-in IP address ID

### Actual Behavior
What actually happened?

* cloudstack_firewall.k8s-firewall: 1 error(s) occurred:

* cloudstack_firewall.k8s-firewall: 1 error(s) occurred:

* CloudStack API error 431 (CSExceptionErrorCode: 4350): Unable to create firewall rule for the IP address ID=25 as IP is not associated with any network and no networkId is passed in

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

Cloudstack 4.9.3.0

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

**Comment by svanharmelen** [comment]
Hi @icornett, it looks like you're using the wrong resource for your setup. It's not very clear from the docs (or from the CloudStack API docs for that matter), but the `cloudstack_firewall` resource only work for IP addresses associated with a guest network.

As you are using a VPC network, the solution is to connect a `cloudstack_network_acl` to your network and then use the `cloudstack_network_acl_rule` resource to configure your rules.

Let me know if this approach does work as expected...

**Comment by icornett** [comment]
Hi @svanharmelen, that did it!  That isn't very well documented anywhere, but that seems to be the way with Cloudstack in general.   Thanks for the assist, this can be closed.
