### ISSUE TITLE
Expected VirtualMachine.ostypeid to be an int64, was a string (on Exoscale)

### ISSUE THREAD

**Issue by gregkare** [terraform-providers/terraform-provider-cloudstack#43]
### Terraform Version
```
Terraform v0.11.10
+ provider.cloudstack v0.1.5
```

Same issue with 0.11.8 (the earliest version I can try, since my state file was last updated using this one), 0.11.9. I have also tried the cloudstack providers version 0.1.0 to 0.1.5

### Affected Resource(s)
- cloudstack_instance

### Terraform Configuration Files

Nothing special, using `cloudstack_instance` among others

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
The state should be successfully refreshed (no changes), as it did until a few weeks ago

### Actual Behavior
```
Error: Error refreshing state: 1 error(s) occurred:

* cloudstack_instance.big_brother_4: 1 error(s) occurred:

* cloudstack_instance.big_brother_4: cloudstack_instance.big_brother_4: json: cannot unmarshal string into Go struct field VirtualMachine.ostypeid of type int64
```

### Steps to Reproduce
1. `terraform refresh`

### Important Factoids
Running on Exoscale. Using the [cs](https://github.com/exoscale/cs) utility I could find out that my instances' ostypeid is "9bdec4b4-9eed-407e-824c-df09f83a7007" (a UUID). Since everything worked until now, maybe this ID used to be an integer and was changed by Exoscale? https://cloudstack.apache.org/api/apidocs-4.11/apis/listVirtualMachines.html does not mention the type of ostypeid. I am also contacting Exoscale to ask them if they changed something in their API recently.

**Comment by greut** [comment]
Hi @gregkare actually it's Exoscale's fault here. Did you try our provider?

https://github.com/exoscale/terraform-provider-exoscale

**Comment by gregkare** [comment]
@greut Hi! Thanks, I did not know there was an exoscale provider. Trying that now.

**Comment by svanharmelen** [comment]
@gregkare does using the Exoscale provider solve your problem? I.e. can this issue be closed?

**Comment by greut** [comment]
@svanharmelen the easy way out of this is, the way I see it:

- for us to release a patched `terraform-provider-cloudstack`
- for us to inform our clients that we are slightly incompatible with upstream cloudstack, and it will get worse (mostly for the better)
- for @gregkare to use the fork'd provider (for now), and migrate to the exoscale provider in the long run...

Does it make sense for you?

**Comment by svanharmelen** [comment]
I guess... But probably @gregkare should answer that :wink: As it will be nasty to use the forked provider in automation (i.e. `terraform init` will always get the official provider).

In the end I think @gregkare needs to plan to switch over to the Exoscale provider. Especially if you foresee more incompatibility issues down the road. But that is up to @gregkare of course!

As for the Exoscale provider, did you ever think about making it an official provider? You can still be the maintainer of the provider but it will then be available when people do `terraform init` and docs can also be found at the Terraform website.

**Comment by mcanevet** [comment]
@greut we hit this bug right now on Exoscale. It is not clear for us what provider we should use : https://github.com/exoscale/terraform-provider-cloudstack/releases or https://github.com/exoscale/terraform-provider-exoscale/releases?

**Comment by greut** [comment]
> As for the Exoscale provider, did you ever think about making it an official provider?

We are in the queue waiting with the others.

@mcanevet I would warmly encourage you to migrate to the `terraform-provider-exoscale` one. It requires a bit of work to reimport everything though.

In the meantime the fork makes it possible to keep using the _cloudstack_ provider. If you need any help with the import, or have missing features, let us know.

**Comment by mcanevet** [comment]
@greut well... I think we unfortunately don't have the choice. We'll probably have to migrate all our Exoscale projects to your provider. That means that we'll have to change our terraform manifests and update the state.
Do you think that something slightly like this could work?
```
terraform state pull | sed 's/cloudstack_/exoscale_/' | terraform state push
```

**Comment by gregkare** [comment]
I'm in the process of importing our existing resources using the terraform-provider-exoscale, I will report back here

**Comment by gregkare** [comment]
Update: I have managed to import all our resources using terraform-provider-exoscale. The biggest change was the security group rules, as with the Exoscale provider the mapping of rules is 1:1 whereas with the cloudstack provider you could have multiple rules.

`cloudstack_instance` becomes `exoscale_compute`, its `service_offering` becomes `size`, its `name` becomes `display_name`, `disk_size` becomes mandatory (integer, size in GB), `security_group_names` becomes `security_groups`, `keypair` becomes `key_pair`

Here's an example:

```
# Before
resource "cloudstack_security_group_rule" "base" {
  security_group_id = "${cloudstack_security_group.base.id}"
  rule {
    protocol                 = "tcp"
    ports                    = ["22", "2222"]
    user_security_group_list = ["SSH Gateway"]
  }

  rule {
    cidr_list = ["0.0.0.0/0"]
    protocol  = "udp"
    ports     = ["60000-61000"]
  }
}

# After
resource "exoscale_security_group_rule" "base" {
  security_group_id = "${exoscale_security_group.base.id}"
  type = "INGRESS"
  protocol = "UDP"
  cidr = "0.0.0.0/0"
  start_port = 60000
  end_port = 61000
}

resource "exoscale_security_group_rule" "base-1" {
  security_group_id = "${exoscale_security_group.base.id}"
  type = "INGRESS"
  protocol = "TCP"
  start_port = 22
  end_port = 22
  user_security_group = "SSH Gateway"
}
```

**Comment by greut** [comment]
@gregkare good job! Thanks for the feedback on your journey, much appreciated.

Yeah... I'm well aware of the limitations on the security group rules... https://github.com/exoscale/terraform-provider-exoscale/issues/194

**Comment by gregkare** [comment]
Closing this one since https://github.com/exoscale/terraform-provider-exoscale works. Thanks
