### ISSUE TITLE
terraform destroy fails when IP is used for source NAT

### ISSUE THREAD

**Issue by gurubert** [terraform-providers/terraform-provider-cloudstack#45]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.11
+ provider.cloudstack v0.1.5

```
cloudstack_firewall.ip-01-fw: Destroying... (ID: 923fb5a0-c029-484b-b7c0-cf468494bf6a)
cloudstack_instance.vm-01: Destroying... (ID: b9249dca-3865-4c22-a9a4-bbae72a2839b)
cloudstack_instance.vm-02: Destroying... (ID: a1299ed4-e140-42e9-9f27-1cafc2d85a59)
cloudstack_egress_firewall.default: Destroying... (ID: 56c51f1b-cd01-43c5-b3a3-bf23816ae683)
cloudstack_firewall.ip-01-fw: Destruction complete after 7s
cloudstack_ipaddress.ip-01: Destroying... (ID: 923fb5a0-c029-484b-b7c0-cf468494bf6a)
cloudstack_instance.vm-01: Still destroying... (ID: b9249dca-3865-4c22-a9a4-bbae72a2839b, 10s elapsed)
cloudstack_egress_firewall.default: Still destroying... (ID: 56c51f1b-cd01-43c5-b3a3-bf23816ae683, 10s elapsed)
cloudstack_instance.vm-02: Still destroying... (ID: a1299ed4-e140-42e9-9f27-1cafc2d85a59, 10s elapsed)
cloudstack_egress_firewall.default: Destruction complete after 17s
cloudstack_instance.vm-02: Still destroying... (ID: a1299ed4-e140-42e9-9f27-1cafc2d85a59, 20s elapsed)
cloudstack_instance.vm-01: Still destroying... (ID: b9249dca-3865-4c22-a9a4-bbae72a2839b, 20s elapsed)
cloudstack_instance.vm-01: Still destroying... (ID: b9249dca-3865-4c22-a9a4-bbae72a2839b, 30s elapsed)
cloudstack_instance.vm-02: Still destroying... (ID: a1299ed4-e140-42e9-9f27-1cafc2d85a59, 30s elapsed)
cloudstack_instance.vm-02: Destruction complete after 37s
cloudstack_instance.vm-01: Still destroying... (ID: b9249dca-3865-4c22-a9a4-bbae72a2839b, 40s elapsed)
cloudstack_instance.vm-01: Destruction complete after 46s

Error: Error applying plan:

1 error(s) occurred:

* cloudstack_ipaddress.ip-01 (destroy): 1 error(s) occurred:

* cloudstack_ipaddress.ip-01: Error disassociating IP address 923fb5a0-c029-484b-b7c0-cf468494bf6a: Undefined error: {"errorcode":530,"errortext":"ip address is used for source nat purposes and can not be disassociated."}
```

The network offering uses the first IP that is created as source NAT. This seems to affect the destruction of this IP. Can this be resolved?

**Comment by svanharmelen** [comment]
Hi @gurubert, thanks for opening this issue! I think the big question is how this is solved by CloudStack itself? So are you able to release/destroy the IP using the web UI or any API calls? As it seems to be a limitation of the current API aka CloudStack itself.

If I'm correct, with older versions of CloudStack a network with the source NAT service would always get an IP for the NAT service when you created the network. It looks like that is now changed which creates this problem.

**Comment by gurubert** [comment]
Cloudstack seems to create this dependency internally.
I am only able to delete the whole network instance via the web UI.
I have no idea how to solve this for "terraform destroy".

**Comment by svanharmelen** [comment]
Thanks for the update. I also thought about this and have an idea how we can solve this issue.

I’m working on updating some other bits as well (as a holiday project) so will add this to my list of things to fix/update.

I expect to be able to release a new version of the provider somewhere during the holidays.
