### ISSUE TITLE
cloudstack_network source_nat_ip does not work

### ISSUE THREAD

**Issue by gurubert** [terraform-providers/terraform-provider-cloudstack#52]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.11
+ provider.cloudstack v0.1.5

### Affected Resource(s)
- cloudstack_network

### Terraform Configuration Files
```hcl
resource "cloudstack_network" "net-01" {
  zone             = "${var.zone}"
  project          = "${var.project}"
  name             = "ceph-tn${var.teilnehmer}-public"
  display_text     = "Ceph Academy TN ${var.teilnehmer} Public"
  cidr             = "${var.cidr}"
  network_domain   = "ceph.heinlein-akademie.de"
  network_offering = "044bb7ec-65af-4c1b-85b8-67bff80e0442"
  source_nat_ip    = true
}
```
The network offering is one including a source NAT service:
```
(local) 🐵 > list networkofferings id=044bb7ec-65af-4c1b-85b8-67bff80e0442
{
  "count": 1,
  "networkoffering": [
    {
      "availability": "Required",
      "conservemode": true,
      "displaytext": "Offering for Isolated networks with Source Nat service enabled",
      "egressdefaultpolicy": false,
      "forvpc": false,
      "guestiptype": "Isolated",
      "id": "044bb7ec-65af-4c1b-85b8-67bff80e0442",
      "isdefault": true,
      "ispersistent": false,
      "name": "DefaultIsolatedNetworkOfferingWithSourceNatService",
      "networkrate": 6000,
      "service": [
        {
          "name": "UserData",
          "provider": [
            {
              "name": "VirtualRouter"
            }
          ]
        },
        {
          "capability": [
            {
              "canchooseservicecapability": false,
              "name": "SupportedSourceNatTypes",
              "value": "peraccount"
            },
            {
              "canchooseservicecapability": false,
              "name": "RedundantRouter",
              "value": "false"
            }
          ],
          "name": "SourceNat",
          "provider": [
            {
              "name": "VirtualRouter"
            }
          ]
        },
        {
          "name": "Vpn",
          "provider": [
            {
              "name": "VirtualRouter"
            }
          ]
        },
        {
          "name": "Dhcp",
          "provider": [
            {
              "name": "VirtualRouter"
            }
          ]
        },
        {
          "capability": [
            {
              "canchooseservicecapability": false,
              "name": "ElasticIp",
              "value": "false"
            },
            {
              "canchooseservicecapability": false,
              "name": "AssociatePublicIP",
              "value": "true"
            }
          ],
          "name": "StaticNat",
          "provider": [
            {
              "name": "VirtualRouter"
            }
          ]
        },
        {
          "name": "PortForwarding",
          "provider": [
            {
              "name": "VirtualRouter"
            }
          ]
        },
        {
          "name": "Dns",
          "provider": [
            {
              "name": "VirtualRouter"
            }
          ]
        },
        {
          "capability": [
            {
              "canchooseservicecapability": false,
              "name": "SupportedLBIsolation",
              "value": "dedicated"
            },
            {
              "canchooseservicecapability": false,
              "name": "ElasticLb",
              "value": "false"
            },
            {
              "canchooseservicecapability": false,
              "name": "InlineMode",
              "value": "false"
            }
          ],
          "name": "Lb",
          "provider": [
            {
              "name": "VirtualRouter"
            }
          ]
        },
        {
          "name": "Firewall",
          "provider": [
            {
              "name": "VirtualRouter"
            }
          ]
        }
      ],
      "serviceofferingid": "0210fb4b-0fd2-4878-90fc-e4e494b034d9",
      "specifyipranges": false,
      "specifyvlan": false,
      "state": "Enabled",
      "supportspublicaccess": false,
      "supportsstrechedl2subnet": false,
      "traffictype": "Guest"
    }
  ]
}
```

### Expected Behavior
A new network with a source NAT IP is created.

### Actual Behavior
terraform stops

### Steps to Reproduce
1. `terraform apply`

**Comment by gurubert** [comment]
The source NAT IP is created even if source_nat_ip is not specified.

**Comment by svanharmelen** [comment]
Hi @gurubert! I thought we already discussed this one in issue #45, but I guess the outcome wasn't mentioned very clearly there.

This is something that changed within CloudStack. With older CS versions you would get a source NAT IP directly when creating a network which supported the source NAT service. Newer versions no longer do this automatically and they require you to add a public IP yourself.

So it's a bit tricky to properly support this from TF as once you add the public IP using the `cloudstack_ip_address` resource, the IP gets _locked_ and you can no longer `destroy` the resource.

To fix this I added a new option to the `cloudstack_network` resource called [`source_nat_ip`](https://www.terraform.io/docs/providers/cloudstack/r/network.html#source_nat_ip) which will add a public IP to the network as soon as the network is created.

**Comment by gurubert** [comment]
The attribute source_nat_ip was not available in version 0.1.5 of the provider but after "terraform apply" nevertheless a source NAT IP had been created.

In version 0.2 of the provider the attribute is available but setting it to "false" on a network offering that includes source natting the effect is that the network is *not* created:

```
Error: Error applying plan:

1 error(s) occurred:

* cloudstack_network.net-02: 1 error(s) occurred:

* cloudstack_network.net-02: Error creating network ceph-tn1-cluster: Get https://apiserver/client/api?apiKey=XYZ&command=createNetwork&displaytext=Network&endip=10.24.5.254&gateway=10.24.5.1&name=network&netmask=255.255.255.0&networkdomain=example.com&networkofferingid=0cfba48f-67d7-4e48-be4b-db96b69f8c28&projectid=8bce21ef-dcc4-4ca7-955b-2060576de563&response=json&startip=10.24.5.2&zoneid=25488fa3-cd04-4e4f-bf61-a79800d2540c&signature=XYZ: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by gurubert** [comment]
The timeout may not be caused by source_nat_ip as I also get it without it. :(

I have ```timeout = "1200"``` in the ```provider "cloudstack"``` section of the terraform file, but this does not seem to help.

Looking into the CloudStack web GUI the network has been created.

**Comment by svanharmelen** [comment]
> The attribute source_nat_ip was not available in version 0.1.5 of the provider but after "terraform apply" nevertheless a source NAT IP had been created.

So in that case it looks like you are using a CloudStack version that still automatically assigns a public IP when a network is created with source NAT support. Can you share which version of CS you are using?

> In version 0.2 of the provider the attribute is available but setting it to "false" on a network offering that includes source natting the effect is that the network is not created:

That should not happen. I'll have a look at that.

**Comment by svanharmelen** [comment]
> I have timeout = "1200" in the provider "cloudstack" section of the terraform file, but this does not seem to help.

No, this timeout is the time allowed for Cloudstack to complete an asynchronous job. But the error you are getting is related to the HTTP client which isn't configurable from the CS provider and which hasn't changed between versions `0.1.5` and `0.2.0`.

So if you use `0.1.5` it works fine and if you switch to `0.2.0` you can this timeout error? And you are using the exact same TF config and CS endpoint?

**Comment by svanharmelen** [comment]
Ah... Then it looks like there is an issue with your local network and/or CloudStack setup causing HTTP requests to take more than 60 seconds to complete. Is your CS service under very high load maybe? Either way these timeouts are, most likely, not an issue with the CS provider.

**Comment by svanharmelen** [comment]
Hi @gurubert! Is this still an issue, or are the timeout errors solved/gone now?

**Comment by gurubert** [comment]
It looks like the timeouts where produced by a non-working network offering that I tried to use.
I was able to resolve this eith the CloudStack team today.
