### ISSUE TITLE
Tags were removed from resources

### ISSUE THREAD

**Issue by cezarsa** [terraform-providers/terraform-provider-cloudstack#57]
In f85ae6c6 every resource containing the `tags` field had this field and the corresponding logic commented out. This code remains commented out on the current master and I wasn't able to find any mention to the fact on the documentation or the release nodes.

Some examples of commented code blocks are:
https://github.com/terraform-providers/terraform-provider-cloudstack/blob/ff819b4ab46e143a333810c51d9080091d0161d0/cloudstack/resource_cloudstack_instance.go#L155
and
https://github.com/terraform-providers/terraform-provider-cloudstack/blob/ff819b4ab46e143a333810c51d9080091d0161d0/cloudstack/resource_cloudstack_instance.go#L287-L289

Was this done by accident, perhaps? If so, would it be okay to simply uncomment the tags and their logic in a pull-request?

**Comment by csquire** [comment]
Can we please get a release that includes this PR?
