### ISSUE TITLE
Error creating the new instance test: json: cannot unmarshal string into Go struct field DeployVirtualMachineResponse.ostypeid of type int64

### ISSUE THREAD

**Issue by Dan-Wolfy** [terraform-providers/terraform-provider-cloudstack#58]
Hi there,

Sorry if this has been mentioned before can't see anything that relates that has been done lately. Guessing its a API mis-match on expected and returned data but could be wrong.

### Terraform Version
Terraform v0.11.11
+ provider.cloudstack v0.1.5
or tried provider.cloudstack v0.1.7

on docker cloudstack/simulator:latest running cloudstack 4.12.0.0-SNAPSHOT

### Affected Resource(s)
cloudstack_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
cloudstack/cloudstack_instance/main.tf
```
resource "cloudstack_instance" "instance" {
  name             = "${var.name}"
  service_offering = "${var.service_offering}"
  template         = "${var.template}"
  zone             = "${var.zone}"
}
```

cloudstack/cloudstack_instance/outputs.tf
```
output "id" {
  value       = "cloudstack_instance.instance.*.id"
  description = "The instance ID"
}

output "display_name" {
  value       = "cloudstack_instance.instance.*.display_name"
  description = "The display name of the instance"
}

```

cloudstack/cloudstack_instance/variables.tf
```
variable "name" {
  description = "The name of the instance"
}

variable "service_offering" {
  description = "The name or ID of the service offering used for this instance"
}

variable "template" {
  description = "The name or ID of the template used for this instance. Changing this forces a new resource to be created"
}

variable "zone" {
  description = "The name or ID of the zone where this instance will be created. Changing this forces a new resource to be created"
}

```

main.tf
```
module "example-instance" {
  source           = "cloudstack/cloudstack_instance"

  name             = "${var.example_name}"
  service_offering = "${var.example-service_offering}"
  template         = "${var.example-instance_template}"
  zone             = "${var.example_zone}"
}
```

variables.tf
```
#defaults
variable "example_zone"             { default = "Sandbox-simulator" }
variable "example-disk_offering"    { default = "PS0" }
variable "example-service_offering" { default = "Small Instance" }
variable "example-network_id"       { default = "admin-network" }

# Example instance
variable "example-instance_template"         { default = "CentOS 5.6 (64-bit) no GUI (Simulator)" }
```

### Debug Output
https://github.com/Dan-Wolfy/brokenstuff/blob/master/terraform-cloudstack/1.txt

### Expected Behavior
Create the VM errorING

### Actual Behavior
Errors and doesn't built terraform.tfstate but manual check via admin GUI shows the instance running.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1) create file;-
docker-compose.yaml
version: '3'
services:
  cloudstack:
    image: cloudstack/simulator:latest
    ports:
      - "8080:8080"
      - "8096:8096"
2) Docker-compose up -d
3) docker exec -ti cloudstackdocker_cloudstack_1 python /root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/basic.cfg
4) `terraform apply`

### Important Factoids
on docker cloudstack/simulator:latest running cloudstack 4.12.0.0-SNAPSHOT
Also tried using the UUIDs instead of names and same error

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
https://github.com/terraform-providers/terraform-provider-cloudstack/issues/43 looks like same issue but different provider.

**Comment by svanharmelen** [comment]
Sorry to hear you are having issues with the CloudStack provider @Dan-Wolfy. This provider currently supports CloudStack <= 4.11.2.0. We try to make it be as backwards compatible as possible, but since API changes are pretty common in the CloudStack API this sometimes isn't possible.

As for your test case, I see you are trying to use the provider with CloudStack 4.12.0.0 which isn't released yet. So there will probably be API changes that cause issues (like the one you encountered) that aren't addressed yet.

Once 4.12.0.0 we will try to update the provider again, but until that time 4.12.0.0 will not be supported.

**Comment by Dan-Wolfy** [comment]
@svanharmelen Cheers for the quick responce, would it be possible to put in the change log the supported version of cloud stack, not sure if it is me but can't seem to see it listed any where. Will retest with the simulator at 4.11.2 thanks

**Comment by svanharmelen** [comment]
You are correct that it's not specifically mentioned, will do that the next time that we update the supported version. As for now, we actually support all current versions. Probably older versions will not work (correctly) anymore but I don't have a way to tell which versions that are exactly.

**Comment by svanharmelen** [comment]
Closing this as there is nothing to fix for this at the moment. Feel free to reopen the issue if you have a need for it.
