### ISSUE TITLE
Cannot upload image for template with from URL ending .img

### ISSUE THREAD

**Issue by 3guboff** [terraform-providers/terraform-provider-cloudstack#59]
### Terraform Version
```
$ terraform -v
Terraform v0.11.11
+ provider.cloudstack v0.2.0
```

### Affected Resource(s)
- cloudstack_template

### Terraform Configuration Files
```
resource "cloudstack_template" "ubuntu_16_04_x64_20190308" {
  name       = "ubuntu-16-04-cloud-20190308"
  format     = "QCOW2"
  hypervisor = "KVM"
  os_type    = "${var.ubuntu_16_04_x64_id}"
  url        = "https://cloud-images.ubuntu.com/xenial/20190308/xenial-server-cloudimg-amd64-disk1.img"
  zone       = "au1"
  is_extractable = true
  is_public = false
  password_enabled = false
  project = "${var.project_id}"
  display_text = "ubuntu-16-04-cloud-20190308 (KVM - QCOW2)"
}
```

### Output
```
* cloudstack_template.ubuntu_16_04_x64_20190308: Error creating template ubuntu-16-04-cloud-20190308: CloudStack API error 431 (CSExceptionErrorCode: 9999): Please specify a valid URL. URL:/xenial/20190308/xenial-server-cloudimg-amd64-uefi1.img is an invalid for the format qcow2
```

### Expected Behavior
Image must be uploaded successfully, even if file from URL with extension **img**

### Actual Behavior
invalid for the format qcow2

**Comment by svanharmelen** [comment]
@3guboff the error you are seeing comes directly from the CS API, so I'm not sure if this is a bug/issue with the template resource.

Did you try to upload the same template manually? And if so, are you a 100% sure that you are using the same settings in here as that you did when uploading it manually (as I notice the format is set to qcow2)?

**Comment by 3guboff** [comment]
@svanharmelen You right man, I'm tryed upload in UI and it's look like this fcking cloudstack have this bug (or feature).
