### ISSUE TITLE
API version too old

### ISSUE THREAD

**Issue by gurubert** [terraform-providers/terraform-provider-cloudstack#67]
Hi,

Running terraform 0.12.7 with the current cloudstack provider gives me the following error:

Error: Failed to instantiate provider "cloudstack" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

Our provider updated their cloudstack installation to 4.11.1.0 recently.

What can we do?

**Comment by svanharmelen** [comment]
Can you post back the output of `terraform version`?

**Comment by gurubert** [comment]
Dang, that was it. I still had the 0.2 version of the cloudstack provider installed. "rm -rf .terraform" and a terraform init installed version 0.3 which has no issues talking to the newer cloudstack API.

**Comment by svanharmelen** [comment]
Cool! Good to hear that works as expected with the latest version 👍
